### ISSUE TITLE
Hey can you detect between authorised and unauthorised human intrusion

### ISSUE THREAD

**Issue by Lawrence27R** [Hyouteki/BTP#3]
Like if a person is valid/authorsied person it will not detect intrusion and if the person is intruder it will send email to the security person.

**Comment by nos1dot618** [comment]
We don't plan no doing that as of yet cause our aim is to detect anomalies which does not involve checking whether it is caused by an authorised user or not.

**Comment by nos1dot618** [comment]
I have a rough idea of how to implement this if we ever were to; it's simple we can include authorised person's photos in the training dataset if we are using object detection as the base so that model give priority to the authorised person rather than the anomaly.
